### ISSUE TITLE
next-remote-watch failing on M1 mac

### ISSUE THREAD

**Issue by glennsarti** [hashicorp/dev-portal#2311]
On a project which uses the dev-portal, It starts the website fine on local dev, however as soon as I save an edited file, I get the following error. In order for me to see the changes, I have to constantly restart node

```text
> Ready on http://localhost:3000
 ✓ Compiled /src/middleware in 271ms (74 modules)
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 ○ Compiling /redacted/docs/[[...page]] ...
 ✓ Compiled /redacted/docs/[[...page]] in 7.2s (3855 modules)
[InstantSearch] The package `react-instantsearch-hooks` is replaced by `react-instantsearch-core`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
[InstantSearch] The package `react-instantsearch-hooks-web` is replaced by `react-instantsearch`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
[InstantSearch] The package `react-instantsearch-hooks` is replaced by `react-instantsearch-core`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
[InstantSearch] The package `react-instantsearch-hooks-web` is replaced by `react-instantsearch`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
 ○ Compiling /api/tutorials-map ...
 ✓ Compiled /api/tutorials-map in 2.6s (1318 modules)
 ✓ Compiled /api/auth/[...nextauth] in 111ms (1328 modules)
[next-auth][warn][NO_SECRET]
https://next-auth.js.org/warnings#no_secret
TypeError: Cannot read properties of undefined (reading 'hotReloader')
    at FSWatcher.<anonymous> (/Users/glennsarti/redacted/website/website-preview/node_modules/next-remote-watch/bin/next-remote-watch:60:22)
    at FSWatcher.emit (node:events:514:28)
    at FSWatcher.emitWithAll (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/index.js:534:8)
    at FSWatcher._emit (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/index.js:626:8)
    at FsEventsHandler.handleEvent (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:288:14)
    at FsEventsHandler.addOrChange (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:238:8)
    at watchCallback (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:342:21)
    at filteredListener (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:127:7)
    at /Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:152:11
    at Set.forEach (<anonymous>)
    at /Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:151:24
 ⨯ unhandledRejection: TypeError: Cannot read properties of undefined (reading 'hotReloader')
    at FSWatcher.<anonymous> (/Users/glennsarti/redacted/website/website-preview/node_modules/next-remote-watch/bin/next-remote-watch:60:22)
    at FSWatcher.emit (node:events:514:28)
    at FSWatcher.emitWithAll (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/index.js:534:8)
    at FSWatcher._emit (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/index.js:626:8)
    at FsEventsHandler.handleEvent (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:288:14)
    at FsEventsHandler.addOrChange (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:238:8)
    at watchCallback (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:342:21)
    at filteredListener (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:127:7)
    at /Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:152:11
    at Set.forEach (<anonymous>)
    at /Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:151:24
 ⨯ unhandledRejection: TypeError: Cannot read properties of undefined (reading 'hotReloader')
    at FSWatcher.<anonymous> (/Users/glennsarti/redacted/website/website-preview/node_modules/next-remote-watch/bin/next-remote-watch:60:22)
    at FSWatcher.emit (node:events:514:28)
    at FSWatcher.emitWithAll (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/index.js:534:8)
    at FSWatcher._emit (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/index.js:626:8)
    at FsEventsHandler.handleEvent (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:288:14)
    at FsEventsHandler.addOrChange (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:238:8)
    at watchCallback (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:342:21)
    at filteredListener (/Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:127:7)
    at /Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:152:11
    at Set.forEach (<anonymous>)
    at /Users/glennsarti/redacted/website/website-preview/node_modules/chokidar/lib/fsevents-handler.js:151:24
[InstantSearch] The package `react-instantsearch-hooks` is replaced by `react-instantsearch-core`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
[InstantSearch] The package `react-instantsearch-hooks-web` is replaced by `react-instantsearch`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
^C
```

It seems like `next-remote-watch` isn't compatible with _something_

node - v18.17.1
npm - 9.6.7
OS - OSX 13.6.3 (M1 architecture)

**Comment by glennsarti** [comment]
I also tried this in a container (using `hashicorp/dev-portal:latest`), thinking it could be my local setup. Nope, same error.

**Comment by glennsarti** [comment]
Still broken

**Comment by heatlikeheatwave** [comment]
Hi @glennsarti, our team's workflow for triaging issues is to open a ticket in the web support slack channel. I advise opening one there about the issue you're having. Thanks!
